import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {ReactNode} from "react";
import {tw} from "@/app/utils/style";
import {AuthProvider} from "@/app/components/AuthContext";
import {ThemeProvider} from "@/app/components/ThemeContext";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface RootLayoutProps {
    children: ReactNode
}

export default function RootLayout({children}: RootLayoutProps) {
    return (
        <html lang="en">
            <body className={tw('bg-neutral-50 dark:bg-zinc-800 text-zinc-900 dark:text-white', 'min-h-screen')} style={inter.style}>
                <ThemeProvider>
                    <AuthProvider>
                        {children}
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
