// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eleven-am/enclave/ent/calllog"
	"github.com/eleven-am/enclave/ent/callparticipant"
	"github.com/eleven-am/enclave/ent/predicate"
	"github.com/eleven-am/enclave/ent/room"
	"github.com/eleven-am/enclave/ent/user"
)

// CallLogQuery is the builder for querying CallLog entities.
type CallLogQuery struct {
	config
	ctx              *QueryContext
	order            []calllog.OrderOption
	inters           []Interceptor
	predicates       []predicate.CallLog
	withInitiator    *UserQuery
	withRoom         *RoomQuery
	withParticipants *CallParticipantQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CallLogQuery builder.
func (clq *CallLogQuery) Where(ps ...predicate.CallLog) *CallLogQuery {
	clq.predicates = append(clq.predicates, ps...)
	return clq
}

// Limit the number of records to be returned by this query.
func (clq *CallLogQuery) Limit(limit int) *CallLogQuery {
	clq.ctx.Limit = &limit
	return clq
}

// Offset to start from.
func (clq *CallLogQuery) Offset(offset int) *CallLogQuery {
	clq.ctx.Offset = &offset
	return clq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (clq *CallLogQuery) Unique(unique bool) *CallLogQuery {
	clq.ctx.Unique = &unique
	return clq
}

// Order specifies how the records should be ordered.
func (clq *CallLogQuery) Order(o ...calllog.OrderOption) *CallLogQuery {
	clq.order = append(clq.order, o...)
	return clq
}

// QueryInitiator chains the current query on the "initiator" edge.
func (clq *CallLogQuery) QueryInitiator() *UserQuery {
	query := (&UserClient{config: clq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := clq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := clq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(calllog.Table, calllog.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, calllog.InitiatorTable, calllog.InitiatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(clq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoom chains the current query on the "room" edge.
func (clq *CallLogQuery) QueryRoom() *RoomQuery {
	query := (&RoomClient{config: clq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := clq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := clq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(calllog.Table, calllog.FieldID, selector),
			sqlgraph.To(room.Table, room.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, calllog.RoomTable, calllog.RoomColumn),
		)
		fromU = sqlgraph.SetNeighbors(clq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParticipants chains the current query on the "participants" edge.
func (clq *CallLogQuery) QueryParticipants() *CallParticipantQuery {
	query := (&CallParticipantClient{config: clq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := clq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := clq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(calllog.Table, calllog.FieldID, selector),
			sqlgraph.To(callparticipant.Table, callparticipant.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, calllog.ParticipantsTable, calllog.ParticipantsColumn),
		)
		fromU = sqlgraph.SetNeighbors(clq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CallLog entity from the query.
// Returns a *NotFoundError when no CallLog was found.
func (clq *CallLogQuery) First(ctx context.Context) (*CallLog, error) {
	nodes, err := clq.Limit(1).All(setContextOp(ctx, clq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{calllog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (clq *CallLogQuery) FirstX(ctx context.Context) *CallLog {
	node, err := clq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CallLog ID from the query.
// Returns a *NotFoundError when no CallLog ID was found.
func (clq *CallLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = clq.Limit(1).IDs(setContextOp(ctx, clq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{calllog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (clq *CallLogQuery) FirstIDX(ctx context.Context) int {
	id, err := clq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CallLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CallLog entity is found.
// Returns a *NotFoundError when no CallLog entities are found.
func (clq *CallLogQuery) Only(ctx context.Context) (*CallLog, error) {
	nodes, err := clq.Limit(2).All(setContextOp(ctx, clq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{calllog.Label}
	default:
		return nil, &NotSingularError{calllog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (clq *CallLogQuery) OnlyX(ctx context.Context) *CallLog {
	node, err := clq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CallLog ID in the query.
// Returns a *NotSingularError when more than one CallLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (clq *CallLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = clq.Limit(2).IDs(setContextOp(ctx, clq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{calllog.Label}
	default:
		err = &NotSingularError{calllog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (clq *CallLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := clq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CallLogs.
func (clq *CallLogQuery) All(ctx context.Context) ([]*CallLog, error) {
	ctx = setContextOp(ctx, clq.ctx, "All")
	if err := clq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CallLog, *CallLogQuery]()
	return withInterceptors[[]*CallLog](ctx, clq, qr, clq.inters)
}

// AllX is like All, but panics if an error occurs.
func (clq *CallLogQuery) AllX(ctx context.Context) []*CallLog {
	nodes, err := clq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CallLog IDs.
func (clq *CallLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if clq.ctx.Unique == nil && clq.path != nil {
		clq.Unique(true)
	}
	ctx = setContextOp(ctx, clq.ctx, "IDs")
	if err = clq.Select(calllog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (clq *CallLogQuery) IDsX(ctx context.Context) []int {
	ids, err := clq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (clq *CallLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, clq.ctx, "Count")
	if err := clq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, clq, querierCount[*CallLogQuery](), clq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (clq *CallLogQuery) CountX(ctx context.Context) int {
	count, err := clq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (clq *CallLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, clq.ctx, "Exist")
	switch _, err := clq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (clq *CallLogQuery) ExistX(ctx context.Context) bool {
	exist, err := clq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CallLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (clq *CallLogQuery) Clone() *CallLogQuery {
	if clq == nil {
		return nil
	}
	return &CallLogQuery{
		config:           clq.config,
		ctx:              clq.ctx.Clone(),
		order:            append([]calllog.OrderOption{}, clq.order...),
		inters:           append([]Interceptor{}, clq.inters...),
		predicates:       append([]predicate.CallLog{}, clq.predicates...),
		withInitiator:    clq.withInitiator.Clone(),
		withRoom:         clq.withRoom.Clone(),
		withParticipants: clq.withParticipants.Clone(),
		// clone intermediate query.
		sql:  clq.sql.Clone(),
		path: clq.path,
	}
}

// WithInitiator tells the query-builder to eager-load the nodes that are connected to
// the "initiator" edge. The optional arguments are used to configure the query builder of the edge.
func (clq *CallLogQuery) WithInitiator(opts ...func(*UserQuery)) *CallLogQuery {
	query := (&UserClient{config: clq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	clq.withInitiator = query
	return clq
}

// WithRoom tells the query-builder to eager-load the nodes that are connected to
// the "room" edge. The optional arguments are used to configure the query builder of the edge.
func (clq *CallLogQuery) WithRoom(opts ...func(*RoomQuery)) *CallLogQuery {
	query := (&RoomClient{config: clq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	clq.withRoom = query
	return clq
}

// WithParticipants tells the query-builder to eager-load the nodes that are connected to
// the "participants" edge. The optional arguments are used to configure the query builder of the edge.
func (clq *CallLogQuery) WithParticipants(opts ...func(*CallParticipantQuery)) *CallLogQuery {
	query := (&CallParticipantClient{config: clq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	clq.withParticipants = query
	return clq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status calllog.Status `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CallLog.Query().
//		GroupBy(calllog.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (clq *CallLogQuery) GroupBy(field string, fields ...string) *CallLogGroupBy {
	clq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CallLogGroupBy{build: clq}
	grbuild.flds = &clq.ctx.Fields
	grbuild.label = calllog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status calllog.Status `json:"status,omitempty"`
//	}
//
//	client.CallLog.Query().
//		Select(calllog.FieldStatus).
//		Scan(ctx, &v)
func (clq *CallLogQuery) Select(fields ...string) *CallLogSelect {
	clq.ctx.Fields = append(clq.ctx.Fields, fields...)
	sbuild := &CallLogSelect{CallLogQuery: clq}
	sbuild.label = calllog.Label
	sbuild.flds, sbuild.scan = &clq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CallLogSelect configured with the given aggregations.
func (clq *CallLogQuery) Aggregate(fns ...AggregateFunc) *CallLogSelect {
	return clq.Select().Aggregate(fns...)
}

func (clq *CallLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range clq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, clq); err != nil {
				return err
			}
		}
	}
	for _, f := range clq.ctx.Fields {
		if !calllog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if clq.path != nil {
		prev, err := clq.path(ctx)
		if err != nil {
			return err
		}
		clq.sql = prev
	}
	return nil
}

func (clq *CallLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CallLog, error) {
	var (
		nodes       = []*CallLog{}
		withFKs     = clq.withFKs
		_spec       = clq.querySpec()
		loadedTypes = [3]bool{
			clq.withInitiator != nil,
			clq.withRoom != nil,
			clq.withParticipants != nil,
		}
	)
	if clq.withInitiator != nil || clq.withRoom != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, calllog.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CallLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CallLog{config: clq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, clq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := clq.withInitiator; query != nil {
		if err := clq.loadInitiator(ctx, query, nodes, nil,
			func(n *CallLog, e *User) { n.Edges.Initiator = e }); err != nil {
			return nil, err
		}
	}
	if query := clq.withRoom; query != nil {
		if err := clq.loadRoom(ctx, query, nodes, nil,
			func(n *CallLog, e *Room) { n.Edges.Room = e }); err != nil {
			return nil, err
		}
	}
	if query := clq.withParticipants; query != nil {
		if err := clq.loadParticipants(ctx, query, nodes,
			func(n *CallLog) { n.Edges.Participants = []*CallParticipant{} },
			func(n *CallLog, e *CallParticipant) { n.Edges.Participants = append(n.Edges.Participants, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (clq *CallLogQuery) loadInitiator(ctx context.Context, query *UserQuery, nodes []*CallLog, init func(*CallLog), assign func(*CallLog, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CallLog)
	for i := range nodes {
		if nodes[i].call_log_initiator == nil {
			continue
		}
		fk := *nodes[i].call_log_initiator
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "call_log_initiator" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (clq *CallLogQuery) loadRoom(ctx context.Context, query *RoomQuery, nodes []*CallLog, init func(*CallLog), assign func(*CallLog, *Room)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CallLog)
	for i := range nodes {
		if nodes[i].call_log_room == nil {
			continue
		}
		fk := *nodes[i].call_log_room
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(room.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "call_log_room" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (clq *CallLogQuery) loadParticipants(ctx context.Context, query *CallParticipantQuery, nodes []*CallLog, init func(*CallLog), assign func(*CallLog, *CallParticipant)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CallLog)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CallParticipant(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(calllog.ParticipantsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.call_participant_call
		if fk == nil {
			return fmt.Errorf(`foreign-key "call_participant_call" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "call_participant_call" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (clq *CallLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := clq.querySpec()
	_spec.Node.Columns = clq.ctx.Fields
	if len(clq.ctx.Fields) > 0 {
		_spec.Unique = clq.ctx.Unique != nil && *clq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, clq.driver, _spec)
}

func (clq *CallLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(calllog.Table, calllog.Columns, sqlgraph.NewFieldSpec(calllog.FieldID, field.TypeInt))
	_spec.From = clq.sql
	if unique := clq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if clq.path != nil {
		_spec.Unique = true
	}
	if fields := clq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, calllog.FieldID)
		for i := range fields {
			if fields[i] != calllog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := clq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := clq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := clq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := clq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (clq *CallLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(clq.driver.Dialect())
	t1 := builder.Table(calllog.Table)
	columns := clq.ctx.Fields
	if len(columns) == 0 {
		columns = calllog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if clq.sql != nil {
		selector = clq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if clq.ctx.Unique != nil && *clq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range clq.predicates {
		p(selector)
	}
	for _, p := range clq.order {
		p(selector)
	}
	if offset := clq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := clq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CallLogGroupBy is the group-by builder for CallLog entities.
type CallLogGroupBy struct {
	selector
	build *CallLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (clgb *CallLogGroupBy) Aggregate(fns ...AggregateFunc) *CallLogGroupBy {
	clgb.fns = append(clgb.fns, fns...)
	return clgb
}

// Scan applies the selector query and scans the result into the given value.
func (clgb *CallLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, clgb.build.ctx, "GroupBy")
	if err := clgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CallLogQuery, *CallLogGroupBy](ctx, clgb.build, clgb, clgb.build.inters, v)
}

func (clgb *CallLogGroupBy) sqlScan(ctx context.Context, root *CallLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(clgb.fns))
	for _, fn := range clgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*clgb.flds)+len(clgb.fns))
		for _, f := range *clgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*clgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := clgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CallLogSelect is the builder for selecting fields of CallLog entities.
type CallLogSelect struct {
	*CallLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cls *CallLogSelect) Aggregate(fns ...AggregateFunc) *CallLogSelect {
	cls.fns = append(cls.fns, fns...)
	return cls
}

// Scan applies the selector query and scans the result into the given value.
func (cls *CallLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cls.ctx, "Select")
	if err := cls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CallLogQuery, *CallLogSelect](ctx, cls.CallLogQuery, cls, cls.inters, v)
}

func (cls *CallLogSelect) sqlScan(ctx context.Context, root *CallLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cls.fns))
	for _, fn := range cls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
