// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eleven-am/enclave/ent/media"
	"github.com/eleven-am/enclave/ent/message"
	"github.com/eleven-am/enclave/ent/predicate"
	"github.com/eleven-am/enclave/ent/room"
	"github.com/eleven-am/enclave/ent/user"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetCipherText sets the "cipher_text" field.
func (mu *MessageUpdate) SetCipherText(s string) *MessageUpdate {
	mu.mutation.SetCipherText(s)
	return mu
}

// SetNillableCipherText sets the "cipher_text" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableCipherText(s *string) *MessageUpdate {
	if s != nil {
		mu.SetCipherText(*s)
	}
	return mu
}

// SetContentType sets the "content_type" field.
func (mu *MessageUpdate) SetContentType(s string) *MessageUpdate {
	mu.mutation.SetContentType(s)
	return mu
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableContentType(s *string) *MessageUpdate {
	if s != nil {
		mu.SetContentType(*s)
	}
	return mu
}

// SetEncryptionScheme sets the "encryption_scheme" field.
func (mu *MessageUpdate) SetEncryptionScheme(s string) *MessageUpdate {
	mu.mutation.SetEncryptionScheme(s)
	return mu
}

// SetNillableEncryptionScheme sets the "encryption_scheme" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableEncryptionScheme(s *string) *MessageUpdate {
	if s != nil {
		mu.SetEncryptionScheme(*s)
	}
	return mu
}

// SetEdited sets the "edited" field.
func (mu *MessageUpdate) SetEdited(b bool) *MessageUpdate {
	mu.mutation.SetEdited(b)
	return mu
}

// SetNillableEdited sets the "edited" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableEdited(b *bool) *MessageUpdate {
	if b != nil {
		mu.SetEdited(*b)
	}
	return mu
}

// SetCreatedAt sets the "created_at" field.
func (mu *MessageUpdate) SetCreatedAt(t time.Time) *MessageUpdate {
	mu.mutation.SetCreatedAt(t)
	return mu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableCreatedAt(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetCreatedAt(*t)
	}
	return mu
}

// SetUpdatedAt sets the "updated_at" field.
func (mu *MessageUpdate) SetUpdatedAt(t time.Time) *MessageUpdate {
	mu.mutation.SetUpdatedAt(t)
	return mu
}

// SetSenderID sets the "sender" edge to the User entity by ID.
func (mu *MessageUpdate) SetSenderID(id int) *MessageUpdate {
	mu.mutation.SetSenderID(id)
	return mu
}

// SetSender sets the "sender" edge to the User entity.
func (mu *MessageUpdate) SetSender(u *User) *MessageUpdate {
	return mu.SetSenderID(u.ID)
}

// SetRoomID sets the "room" edge to the Room entity by ID.
func (mu *MessageUpdate) SetRoomID(id int) *MessageUpdate {
	mu.mutation.SetRoomID(id)
	return mu
}

// SetRoom sets the "room" edge to the Room entity.
func (mu *MessageUpdate) SetRoom(r *Room) *MessageUpdate {
	return mu.SetRoomID(r.ID)
}

// AddMediumIDs adds the "media" edge to the Media entity by IDs.
func (mu *MessageUpdate) AddMediumIDs(ids ...int) *MessageUpdate {
	mu.mutation.AddMediumIDs(ids...)
	return mu
}

// AddMedia adds the "media" edges to the Media entity.
func (mu *MessageUpdate) AddMedia(m ...*Media) *MessageUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mu.AddMediumIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// ClearSender clears the "sender" edge to the User entity.
func (mu *MessageUpdate) ClearSender() *MessageUpdate {
	mu.mutation.ClearSender()
	return mu
}

// ClearRoom clears the "room" edge to the Room entity.
func (mu *MessageUpdate) ClearRoom() *MessageUpdate {
	mu.mutation.ClearRoom()
	return mu
}

// ClearMedia clears all "media" edges to the Media entity.
func (mu *MessageUpdate) ClearMedia() *MessageUpdate {
	mu.mutation.ClearMedia()
	return mu
}

// RemoveMediumIDs removes the "media" edge to Media entities by IDs.
func (mu *MessageUpdate) RemoveMediumIDs(ids ...int) *MessageUpdate {
	mu.mutation.RemoveMediumIDs(ids...)
	return mu
}

// RemoveMedia removes "media" edges to Media entities.
func (mu *MessageUpdate) RemoveMedia(m ...*Media) *MessageUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mu.RemoveMediumIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	mu.defaults()
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mu *MessageUpdate) defaults() {
	if _, ok := mu.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		mu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if v, ok := mu.mutation.CipherText(); ok {
		if err := message.CipherTextValidator(v); err != nil {
			return &ValidationError{Name: "cipher_text", err: fmt.Errorf(`ent: validator failed for field "Message.cipher_text": %w`, err)}
		}
	}
	if _, ok := mu.mutation.SenderID(); mu.mutation.SenderCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Message.sender"`)
	}
	if _, ok := mu.mutation.RoomID(); mu.mutation.RoomCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Message.room"`)
	}
	return nil
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.CipherText(); ok {
		_spec.SetField(message.FieldCipherText, field.TypeString, value)
	}
	if value, ok := mu.mutation.ContentType(); ok {
		_spec.SetField(message.FieldContentType, field.TypeString, value)
	}
	if value, ok := mu.mutation.EncryptionScheme(); ok {
		_spec.SetField(message.FieldEncryptionScheme, field.TypeString, value)
	}
	if value, ok := mu.mutation.Edited(); ok {
		_spec.SetField(message.FieldEdited, field.TypeBool, value)
	}
	if value, ok := mu.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := mu.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
	}
	if mu.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.SenderTable,
			Columns: []string{message.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.SenderTable,
			Columns: []string{message.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.RoomTable,
			Columns: []string{message.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.RoomTable,
			Columns: []string{message.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.MediaTable,
			Columns: []string{message.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedMediaIDs(); len(nodes) > 0 && !mu.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.MediaTable,
			Columns: []string{message.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.MediaTable,
			Columns: []string{message.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetCipherText sets the "cipher_text" field.
func (muo *MessageUpdateOne) SetCipherText(s string) *MessageUpdateOne {
	muo.mutation.SetCipherText(s)
	return muo
}

// SetNillableCipherText sets the "cipher_text" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableCipherText(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetCipherText(*s)
	}
	return muo
}

// SetContentType sets the "content_type" field.
func (muo *MessageUpdateOne) SetContentType(s string) *MessageUpdateOne {
	muo.mutation.SetContentType(s)
	return muo
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableContentType(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetContentType(*s)
	}
	return muo
}

// SetEncryptionScheme sets the "encryption_scheme" field.
func (muo *MessageUpdateOne) SetEncryptionScheme(s string) *MessageUpdateOne {
	muo.mutation.SetEncryptionScheme(s)
	return muo
}

// SetNillableEncryptionScheme sets the "encryption_scheme" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableEncryptionScheme(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetEncryptionScheme(*s)
	}
	return muo
}

// SetEdited sets the "edited" field.
func (muo *MessageUpdateOne) SetEdited(b bool) *MessageUpdateOne {
	muo.mutation.SetEdited(b)
	return muo
}

// SetNillableEdited sets the "edited" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableEdited(b *bool) *MessageUpdateOne {
	if b != nil {
		muo.SetEdited(*b)
	}
	return muo
}

// SetCreatedAt sets the "created_at" field.
func (muo *MessageUpdateOne) SetCreatedAt(t time.Time) *MessageUpdateOne {
	muo.mutation.SetCreatedAt(t)
	return muo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableCreatedAt(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetCreatedAt(*t)
	}
	return muo
}

// SetUpdatedAt sets the "updated_at" field.
func (muo *MessageUpdateOne) SetUpdatedAt(t time.Time) *MessageUpdateOne {
	muo.mutation.SetUpdatedAt(t)
	return muo
}

// SetSenderID sets the "sender" edge to the User entity by ID.
func (muo *MessageUpdateOne) SetSenderID(id int) *MessageUpdateOne {
	muo.mutation.SetSenderID(id)
	return muo
}

// SetSender sets the "sender" edge to the User entity.
func (muo *MessageUpdateOne) SetSender(u *User) *MessageUpdateOne {
	return muo.SetSenderID(u.ID)
}

// SetRoomID sets the "room" edge to the Room entity by ID.
func (muo *MessageUpdateOne) SetRoomID(id int) *MessageUpdateOne {
	muo.mutation.SetRoomID(id)
	return muo
}

// SetRoom sets the "room" edge to the Room entity.
func (muo *MessageUpdateOne) SetRoom(r *Room) *MessageUpdateOne {
	return muo.SetRoomID(r.ID)
}

// AddMediumIDs adds the "media" edge to the Media entity by IDs.
func (muo *MessageUpdateOne) AddMediumIDs(ids ...int) *MessageUpdateOne {
	muo.mutation.AddMediumIDs(ids...)
	return muo
}

// AddMedia adds the "media" edges to the Media entity.
func (muo *MessageUpdateOne) AddMedia(m ...*Media) *MessageUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return muo.AddMediumIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// ClearSender clears the "sender" edge to the User entity.
func (muo *MessageUpdateOne) ClearSender() *MessageUpdateOne {
	muo.mutation.ClearSender()
	return muo
}

// ClearRoom clears the "room" edge to the Room entity.
func (muo *MessageUpdateOne) ClearRoom() *MessageUpdateOne {
	muo.mutation.ClearRoom()
	return muo
}

// ClearMedia clears all "media" edges to the Media entity.
func (muo *MessageUpdateOne) ClearMedia() *MessageUpdateOne {
	muo.mutation.ClearMedia()
	return muo
}

// RemoveMediumIDs removes the "media" edge to Media entities by IDs.
func (muo *MessageUpdateOne) RemoveMediumIDs(ids ...int) *MessageUpdateOne {
	muo.mutation.RemoveMediumIDs(ids...)
	return muo
}

// RemoveMedia removes "media" edges to Media entities.
func (muo *MessageUpdateOne) RemoveMedia(m ...*Media) *MessageUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return muo.RemoveMediumIDs(ids...)
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	muo.defaults()
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (muo *MessageUpdateOne) defaults() {
	if _, ok := muo.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		muo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if v, ok := muo.mutation.CipherText(); ok {
		if err := message.CipherTextValidator(v); err != nil {
			return &ValidationError{Name: "cipher_text", err: fmt.Errorf(`ent: validator failed for field "Message.cipher_text": %w`, err)}
		}
	}
	if _, ok := muo.mutation.SenderID(); muo.mutation.SenderCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Message.sender"`)
	}
	if _, ok := muo.mutation.RoomID(); muo.mutation.RoomCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Message.room"`)
	}
	return nil
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.CipherText(); ok {
		_spec.SetField(message.FieldCipherText, field.TypeString, value)
	}
	if value, ok := muo.mutation.ContentType(); ok {
		_spec.SetField(message.FieldContentType, field.TypeString, value)
	}
	if value, ok := muo.mutation.EncryptionScheme(); ok {
		_spec.SetField(message.FieldEncryptionScheme, field.TypeString, value)
	}
	if value, ok := muo.mutation.Edited(); ok {
		_spec.SetField(message.FieldEdited, field.TypeBool, value)
	}
	if value, ok := muo.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := muo.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
	}
	if muo.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.SenderTable,
			Columns: []string{message.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.SenderTable,
			Columns: []string{message.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.RoomTable,
			Columns: []string{message.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.RoomTable,
			Columns: []string{message.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.MediaTable,
			Columns: []string{message.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedMediaIDs(); len(nodes) > 0 && !muo.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.MediaTable,
			Columns: []string{message.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.MediaTable,
			Columns: []string{message.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
