// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eleven-am/enclave/ent/message"
	"github.com/eleven-am/enclave/ent/notification"
	"github.com/eleven-am/enclave/ent/room"
	"github.com/eleven-am/enclave/ent/user"
)

// NotificationCreate is the builder for creating a Notification entity.
type NotificationCreate struct {
	config
	mutation *NotificationMutation
	hooks    []Hook
}

// SetKind sets the "kind" field.
func (nc *NotificationCreate) SetKind(s string) *NotificationCreate {
	nc.mutation.SetKind(s)
	return nc
}

// SetCipherText sets the "cipher_text" field.
func (nc *NotificationCreate) SetCipherText(s string) *NotificationCreate {
	nc.mutation.SetCipherText(s)
	return nc
}

// SetEncryptionScheme sets the "encryption_scheme" field.
func (nc *NotificationCreate) SetEncryptionScheme(s string) *NotificationCreate {
	nc.mutation.SetEncryptionScheme(s)
	return nc
}

// SetNillableEncryptionScheme sets the "encryption_scheme" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableEncryptionScheme(s *string) *NotificationCreate {
	if s != nil {
		nc.SetEncryptionScheme(*s)
	}
	return nc
}

// SetRead sets the "read" field.
func (nc *NotificationCreate) SetRead(b bool) *NotificationCreate {
	nc.mutation.SetRead(b)
	return nc
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableRead(b *bool) *NotificationCreate {
	if b != nil {
		nc.SetRead(*b)
	}
	return nc
}

// SetCreatedAt sets the "created_at" field.
func (nc *NotificationCreate) SetCreatedAt(t time.Time) *NotificationCreate {
	nc.mutation.SetCreatedAt(t)
	return nc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableCreatedAt(t *time.Time) *NotificationCreate {
	if t != nil {
		nc.SetCreatedAt(*t)
	}
	return nc
}

// SetUpdatedAt sets the "updated_at" field.
func (nc *NotificationCreate) SetUpdatedAt(t time.Time) *NotificationCreate {
	nc.mutation.SetUpdatedAt(t)
	return nc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (nc *NotificationCreate) SetNillableUpdatedAt(t *time.Time) *NotificationCreate {
	if t != nil {
		nc.SetUpdatedAt(*t)
	}
	return nc
}

// SetRecipientID sets the "recipient" edge to the User entity by ID.
func (nc *NotificationCreate) SetRecipientID(id int) *NotificationCreate {
	nc.mutation.SetRecipientID(id)
	return nc
}

// SetRecipient sets the "recipient" edge to the User entity.
func (nc *NotificationCreate) SetRecipient(u *User) *NotificationCreate {
	return nc.SetRecipientID(u.ID)
}

// SetRoomID sets the "room" edge to the Room entity by ID.
func (nc *NotificationCreate) SetRoomID(id int) *NotificationCreate {
	nc.mutation.SetRoomID(id)
	return nc
}

// SetNillableRoomID sets the "room" edge to the Room entity by ID if the given value is not nil.
func (nc *NotificationCreate) SetNillableRoomID(id *int) *NotificationCreate {
	if id != nil {
		nc = nc.SetRoomID(*id)
	}
	return nc
}

// SetRoom sets the "room" edge to the Room entity.
func (nc *NotificationCreate) SetRoom(r *Room) *NotificationCreate {
	return nc.SetRoomID(r.ID)
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (nc *NotificationCreate) SetMessageID(id int) *NotificationCreate {
	nc.mutation.SetMessageID(id)
	return nc
}

// SetNillableMessageID sets the "message" edge to the Message entity by ID if the given value is not nil.
func (nc *NotificationCreate) SetNillableMessageID(id *int) *NotificationCreate {
	if id != nil {
		nc = nc.SetMessageID(*id)
	}
	return nc
}

// SetMessage sets the "message" edge to the Message entity.
func (nc *NotificationCreate) SetMessage(m *Message) *NotificationCreate {
	return nc.SetMessageID(m.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (nc *NotificationCreate) Mutation() *NotificationMutation {
	return nc.mutation
}

// Save creates the Notification in the database.
func (nc *NotificationCreate) Save(ctx context.Context) (*Notification, error) {
	nc.defaults()
	return withHooks(ctx, nc.sqlSave, nc.mutation, nc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NotificationCreate) SaveX(ctx context.Context) *Notification {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nc *NotificationCreate) Exec(ctx context.Context) error {
	_, err := nc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nc *NotificationCreate) ExecX(ctx context.Context) {
	if err := nc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nc *NotificationCreate) defaults() {
	if _, ok := nc.mutation.EncryptionScheme(); !ok {
		v := notification.DefaultEncryptionScheme
		nc.mutation.SetEncryptionScheme(v)
	}
	if _, ok := nc.mutation.Read(); !ok {
		v := notification.DefaultRead
		nc.mutation.SetRead(v)
	}
	if _, ok := nc.mutation.CreatedAt(); !ok {
		v := notification.DefaultCreatedAt()
		nc.mutation.SetCreatedAt(v)
	}
	if _, ok := nc.mutation.UpdatedAt(); !ok {
		v := notification.DefaultUpdatedAt()
		nc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NotificationCreate) check() error {
	if _, ok := nc.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Notification.kind"`)}
	}
	if v, ok := nc.mutation.Kind(); ok {
		if err := notification.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Notification.kind": %w`, err)}
		}
	}
	if _, ok := nc.mutation.CipherText(); !ok {
		return &ValidationError{Name: "cipher_text", err: errors.New(`ent: missing required field "Notification.cipher_text"`)}
	}
	if v, ok := nc.mutation.CipherText(); ok {
		if err := notification.CipherTextValidator(v); err != nil {
			return &ValidationError{Name: "cipher_text", err: fmt.Errorf(`ent: validator failed for field "Notification.cipher_text": %w`, err)}
		}
	}
	if _, ok := nc.mutation.EncryptionScheme(); !ok {
		return &ValidationError{Name: "encryption_scheme", err: errors.New(`ent: missing required field "Notification.encryption_scheme"`)}
	}
	if _, ok := nc.mutation.Read(); !ok {
		return &ValidationError{Name: "read", err: errors.New(`ent: missing required field "Notification.read"`)}
	}
	if _, ok := nc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Notification.created_at"`)}
	}
	if _, ok := nc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Notification.updated_at"`)}
	}
	if _, ok := nc.mutation.RecipientID(); !ok {
		return &ValidationError{Name: "recipient", err: errors.New(`ent: missing required edge "Notification.recipient"`)}
	}
	return nil
}

func (nc *NotificationCreate) sqlSave(ctx context.Context) (*Notification, error) {
	if err := nc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	nc.mutation.id = &_node.ID
	nc.mutation.done = true
	return _node, nil
}

func (nc *NotificationCreate) createSpec() (*Notification, *sqlgraph.CreateSpec) {
	var (
		_node = &Notification{config: nc.config}
		_spec = sqlgraph.NewCreateSpec(notification.Table, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	)
	if value, ok := nc.mutation.Kind(); ok {
		_spec.SetField(notification.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := nc.mutation.CipherText(); ok {
		_spec.SetField(notification.FieldCipherText, field.TypeString, value)
		_node.CipherText = value
	}
	if value, ok := nc.mutation.EncryptionScheme(); ok {
		_spec.SetField(notification.FieldEncryptionScheme, field.TypeString, value)
		_node.EncryptionScheme = value
	}
	if value, ok := nc.mutation.Read(); ok {
		_spec.SetField(notification.FieldRead, field.TypeBool, value)
		_node.Read = value
	}
	if value, ok := nc.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := nc.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := nc.mutation.RecipientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notification.RecipientTable,
			Columns: []string{notification.RecipientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.notification_recipient = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := nc.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notification.RoomTable,
			Columns: []string{notification.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.notification_room = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := nc.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notification.MessageTable,
			Columns: []string{notification.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.notification_message = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationCreateBulk is the builder for creating many Notification entities in bulk.
type NotificationCreateBulk struct {
	config
	err      error
	builders []*NotificationCreate
}

// Save creates the Notification entities in the database.
func (ncb *NotificationCreateBulk) Save(ctx context.Context) ([]*Notification, error) {
	if ncb.err != nil {
		return nil, ncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*Notification, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NotificationCreateBulk) SaveX(ctx context.Context) []*Notification {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncb *NotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := ncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncb *NotificationCreateBulk) ExecX(ctx context.Context) {
	if err := ncb.Exec(ctx); err != nil {
		panic(err)
	}
}
