// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/eleven-am/enclave/ent/room"
	"github.com/eleven-am/enclave/ent/roommembership"
	"github.com/eleven-am/enclave/ent/user"
)

// RoomMembership is the model entity for the RoomMembership schema.
type RoomMembership struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Role holds the value of the "role" field.
	Role roommembership.Role `json:"role,omitempty"`
	// CanPost holds the value of the "can_post" field.
	CanPost bool `json:"can_post,omitempty"`
	// CanCall holds the value of the "can_call" field.
	CanCall bool `json:"can_call,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoomMembershipQuery when eager-loading is set.
	Edges                RoomMembershipEdges `json:"edges"`
	room_membership_user *int
	room_membership_room *int
	selectValues         sql.SelectValues
}

// RoomMembershipEdges holds the relations/edges for other nodes in the graph.
type RoomMembershipEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Room holds the value of the room edge.
	Room *Room `json:"room,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RoomMembershipEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// RoomOrErr returns the Room value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RoomMembershipEdges) RoomOrErr() (*Room, error) {
	if e.Room != nil {
		return e.Room, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: room.Label}
	}
	return nil, &NotLoadedError{edge: "room"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RoomMembership) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case roommembership.FieldCanPost, roommembership.FieldCanCall:
			values[i] = new(sql.NullBool)
		case roommembership.FieldID:
			values[i] = new(sql.NullInt64)
		case roommembership.FieldRole:
			values[i] = new(sql.NullString)
		case roommembership.FieldJoinedAt, roommembership.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case roommembership.ForeignKeys[0]: // room_membership_user
			values[i] = new(sql.NullInt64)
		case roommembership.ForeignKeys[1]: // room_membership_room
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RoomMembership fields.
func (rm *RoomMembership) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case roommembership.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rm.ID = int(value.Int64)
		case roommembership.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				rm.Role = roommembership.Role(value.String)
			}
		case roommembership.FieldCanPost:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_post", values[i])
			} else if value.Valid {
				rm.CanPost = value.Bool
			}
		case roommembership.FieldCanCall:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_call", values[i])
			} else if value.Valid {
				rm.CanCall = value.Bool
			}
		case roommembership.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				rm.JoinedAt = value.Time
			}
		case roommembership.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				rm.UpdatedAt = value.Time
			}
		case roommembership.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field room_membership_user", value)
			} else if value.Valid {
				rm.room_membership_user = new(int)
				*rm.room_membership_user = int(value.Int64)
			}
		case roommembership.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field room_membership_room", value)
			} else if value.Valid {
				rm.room_membership_room = new(int)
				*rm.room_membership_room = int(value.Int64)
			}
		default:
			rm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RoomMembership.
// This includes values selected through modifiers, order, etc.
func (rm *RoomMembership) Value(name string) (ent.Value, error) {
	return rm.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the RoomMembership entity.
func (rm *RoomMembership) QueryUser() *UserQuery {
	return NewRoomMembershipClient(rm.config).QueryUser(rm)
}

// QueryRoom queries the "room" edge of the RoomMembership entity.
func (rm *RoomMembership) QueryRoom() *RoomQuery {
	return NewRoomMembershipClient(rm.config).QueryRoom(rm)
}

// Update returns a builder for updating this RoomMembership.
// Note that you need to call RoomMembership.Unwrap() before calling this method if this RoomMembership
// was returned from a transaction, and the transaction was committed or rolled back.
func (rm *RoomMembership) Update() *RoomMembershipUpdateOne {
	return NewRoomMembershipClient(rm.config).UpdateOne(rm)
}

// Unwrap unwraps the RoomMembership entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rm *RoomMembership) Unwrap() *RoomMembership {
	_tx, ok := rm.config.driver.(*txDriver)
	if !ok {
		panic("ent: RoomMembership is not a transactional entity")
	}
	rm.config.driver = _tx.drv
	return rm
}

// String implements the fmt.Stringer.
func (rm *RoomMembership) String() string {
	var builder strings.Builder
	builder.WriteString("RoomMembership(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rm.ID))
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", rm.Role))
	builder.WriteString(", ")
	builder.WriteString("can_post=")
	builder.WriteString(fmt.Sprintf("%v", rm.CanPost))
	builder.WriteString(", ")
	builder.WriteString("can_call=")
	builder.WriteString(fmt.Sprintf("%v", rm.CanCall))
	builder.WriteString(", ")
	builder.WriteString("joined_at=")
	builder.WriteString(rm.JoinedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(rm.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RoomMemberships is a parsable slice of RoomMembership.
type RoomMemberships []*RoomMembership
