// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eleven-am/enclave/ent/predicate"
	"github.com/eleven-am/enclave/ent/roommembership"
)

// RoomMembershipDelete is the builder for deleting a RoomMembership entity.
type RoomMembershipDelete struct {
	config
	hooks    []Hook
	mutation *RoomMembershipMutation
}

// Where appends a list predicates to the RoomMembershipDelete builder.
func (rmd *RoomMembershipDelete) Where(ps ...predicate.RoomMembership) *RoomMembershipDelete {
	rmd.mutation.Where(ps...)
	return rmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rmd *RoomMembershipDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rmd.sqlExec, rmd.mutation, rmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rmd *RoomMembershipDelete) ExecX(ctx context.Context) int {
	n, err := rmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rmd *RoomMembershipDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(roommembership.Table, sqlgraph.NewFieldSpec(roommembership.FieldID, field.TypeInt))
	if ps := rmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rmd.mutation.done = true
	return affected, err
}

// RoomMembershipDeleteOne is the builder for deleting a single RoomMembership entity.
type RoomMembershipDeleteOne struct {
	rmd *RoomMembershipDelete
}

// Where appends a list predicates to the RoomMembershipDelete builder.
func (rmdo *RoomMembershipDeleteOne) Where(ps ...predicate.RoomMembership) *RoomMembershipDeleteOne {
	rmdo.rmd.mutation.Where(ps...)
	return rmdo
}

// Exec executes the deletion query.
func (rmdo *RoomMembershipDeleteOne) Exec(ctx context.Context) error {
	n, err := rmdo.rmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{roommembership.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rmdo *RoomMembershipDeleteOne) ExecX(ctx context.Context) {
	if err := rmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
