// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eleven-am/enclave/ent/predicate"
	"github.com/eleven-am/enclave/ent/room"
	"github.com/eleven-am/enclave/ent/roommembership"
	"github.com/eleven-am/enclave/ent/user"
)

// RoomMembershipQuery is the builder for querying RoomMembership entities.
type RoomMembershipQuery struct {
	config
	ctx        *QueryContext
	order      []roommembership.OrderOption
	inters     []Interceptor
	predicates []predicate.RoomMembership
	withUser   *UserQuery
	withRoom   *RoomQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoomMembershipQuery builder.
func (rmq *RoomMembershipQuery) Where(ps ...predicate.RoomMembership) *RoomMembershipQuery {
	rmq.predicates = append(rmq.predicates, ps...)
	return rmq
}

// Limit the number of records to be returned by this query.
func (rmq *RoomMembershipQuery) Limit(limit int) *RoomMembershipQuery {
	rmq.ctx.Limit = &limit
	return rmq
}

// Offset to start from.
func (rmq *RoomMembershipQuery) Offset(offset int) *RoomMembershipQuery {
	rmq.ctx.Offset = &offset
	return rmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rmq *RoomMembershipQuery) Unique(unique bool) *RoomMembershipQuery {
	rmq.ctx.Unique = &unique
	return rmq
}

// Order specifies how the records should be ordered.
func (rmq *RoomMembershipQuery) Order(o ...roommembership.OrderOption) *RoomMembershipQuery {
	rmq.order = append(rmq.order, o...)
	return rmq
}

// QueryUser chains the current query on the "user" edge.
func (rmq *RoomMembershipQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: rmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roommembership.Table, roommembership.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, roommembership.UserTable, roommembership.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(rmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoom chains the current query on the "room" edge.
func (rmq *RoomMembershipQuery) QueryRoom() *RoomQuery {
	query := (&RoomClient{config: rmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roommembership.Table, roommembership.FieldID, selector),
			sqlgraph.To(room.Table, room.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, roommembership.RoomTable, roommembership.RoomColumn),
		)
		fromU = sqlgraph.SetNeighbors(rmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RoomMembership entity from the query.
// Returns a *NotFoundError when no RoomMembership was found.
func (rmq *RoomMembershipQuery) First(ctx context.Context) (*RoomMembership, error) {
	nodes, err := rmq.Limit(1).All(setContextOp(ctx, rmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{roommembership.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rmq *RoomMembershipQuery) FirstX(ctx context.Context) *RoomMembership {
	node, err := rmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoomMembership ID from the query.
// Returns a *NotFoundError when no RoomMembership ID was found.
func (rmq *RoomMembershipQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rmq.Limit(1).IDs(setContextOp(ctx, rmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roommembership.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rmq *RoomMembershipQuery) FirstIDX(ctx context.Context) int {
	id, err := rmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoomMembership entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoomMembership entity is found.
// Returns a *NotFoundError when no RoomMembership entities are found.
func (rmq *RoomMembershipQuery) Only(ctx context.Context) (*RoomMembership, error) {
	nodes, err := rmq.Limit(2).All(setContextOp(ctx, rmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{roommembership.Label}
	default:
		return nil, &NotSingularError{roommembership.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rmq *RoomMembershipQuery) OnlyX(ctx context.Context) *RoomMembership {
	node, err := rmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoomMembership ID in the query.
// Returns a *NotSingularError when more than one RoomMembership ID is found.
// Returns a *NotFoundError when no entities are found.
func (rmq *RoomMembershipQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rmq.Limit(2).IDs(setContextOp(ctx, rmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roommembership.Label}
	default:
		err = &NotSingularError{roommembership.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rmq *RoomMembershipQuery) OnlyIDX(ctx context.Context) int {
	id, err := rmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoomMemberships.
func (rmq *RoomMembershipQuery) All(ctx context.Context) ([]*RoomMembership, error) {
	ctx = setContextOp(ctx, rmq.ctx, "All")
	if err := rmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RoomMembership, *RoomMembershipQuery]()
	return withInterceptors[[]*RoomMembership](ctx, rmq, qr, rmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rmq *RoomMembershipQuery) AllX(ctx context.Context) []*RoomMembership {
	nodes, err := rmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoomMembership IDs.
func (rmq *RoomMembershipQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rmq.ctx.Unique == nil && rmq.path != nil {
		rmq.Unique(true)
	}
	ctx = setContextOp(ctx, rmq.ctx, "IDs")
	if err = rmq.Select(roommembership.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rmq *RoomMembershipQuery) IDsX(ctx context.Context) []int {
	ids, err := rmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rmq *RoomMembershipQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rmq.ctx, "Count")
	if err := rmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rmq, querierCount[*RoomMembershipQuery](), rmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rmq *RoomMembershipQuery) CountX(ctx context.Context) int {
	count, err := rmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rmq *RoomMembershipQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rmq.ctx, "Exist")
	switch _, err := rmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rmq *RoomMembershipQuery) ExistX(ctx context.Context) bool {
	exist, err := rmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoomMembershipQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rmq *RoomMembershipQuery) Clone() *RoomMembershipQuery {
	if rmq == nil {
		return nil
	}
	return &RoomMembershipQuery{
		config:     rmq.config,
		ctx:        rmq.ctx.Clone(),
		order:      append([]roommembership.OrderOption{}, rmq.order...),
		inters:     append([]Interceptor{}, rmq.inters...),
		predicates: append([]predicate.RoomMembership{}, rmq.predicates...),
		withUser:   rmq.withUser.Clone(),
		withRoom:   rmq.withRoom.Clone(),
		// clone intermediate query.
		sql:  rmq.sql.Clone(),
		path: rmq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (rmq *RoomMembershipQuery) WithUser(opts ...func(*UserQuery)) *RoomMembershipQuery {
	query := (&UserClient{config: rmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rmq.withUser = query
	return rmq
}

// WithRoom tells the query-builder to eager-load the nodes that are connected to
// the "room" edge. The optional arguments are used to configure the query builder of the edge.
func (rmq *RoomMembershipQuery) WithRoom(opts ...func(*RoomQuery)) *RoomMembershipQuery {
	query := (&RoomClient{config: rmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rmq.withRoom = query
	return rmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Role roommembership.Role `json:"role,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoomMembership.Query().
//		GroupBy(roommembership.FieldRole).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rmq *RoomMembershipQuery) GroupBy(field string, fields ...string) *RoomMembershipGroupBy {
	rmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoomMembershipGroupBy{build: rmq}
	grbuild.flds = &rmq.ctx.Fields
	grbuild.label = roommembership.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Role roommembership.Role `json:"role,omitempty"`
//	}
//
//	client.RoomMembership.Query().
//		Select(roommembership.FieldRole).
//		Scan(ctx, &v)
func (rmq *RoomMembershipQuery) Select(fields ...string) *RoomMembershipSelect {
	rmq.ctx.Fields = append(rmq.ctx.Fields, fields...)
	sbuild := &RoomMembershipSelect{RoomMembershipQuery: rmq}
	sbuild.label = roommembership.Label
	sbuild.flds, sbuild.scan = &rmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoomMembershipSelect configured with the given aggregations.
func (rmq *RoomMembershipQuery) Aggregate(fns ...AggregateFunc) *RoomMembershipSelect {
	return rmq.Select().Aggregate(fns...)
}

func (rmq *RoomMembershipQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rmq); err != nil {
				return err
			}
		}
	}
	for _, f := range rmq.ctx.Fields {
		if !roommembership.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rmq.path != nil {
		prev, err := rmq.path(ctx)
		if err != nil {
			return err
		}
		rmq.sql = prev
	}
	return nil
}

func (rmq *RoomMembershipQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoomMembership, error) {
	var (
		nodes       = []*RoomMembership{}
		withFKs     = rmq.withFKs
		_spec       = rmq.querySpec()
		loadedTypes = [2]bool{
			rmq.withUser != nil,
			rmq.withRoom != nil,
		}
	)
	if rmq.withUser != nil || rmq.withRoom != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, roommembership.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RoomMembership).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RoomMembership{config: rmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rmq.withUser; query != nil {
		if err := rmq.loadUser(ctx, query, nodes, nil,
			func(n *RoomMembership, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := rmq.withRoom; query != nil {
		if err := rmq.loadRoom(ctx, query, nodes, nil,
			func(n *RoomMembership, e *Room) { n.Edges.Room = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rmq *RoomMembershipQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*RoomMembership, init func(*RoomMembership), assign func(*RoomMembership, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RoomMembership)
	for i := range nodes {
		if nodes[i].room_membership_user == nil {
			continue
		}
		fk := *nodes[i].room_membership_user
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "room_membership_user" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rmq *RoomMembershipQuery) loadRoom(ctx context.Context, query *RoomQuery, nodes []*RoomMembership, init func(*RoomMembership), assign func(*RoomMembership, *Room)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RoomMembership)
	for i := range nodes {
		if nodes[i].room_membership_room == nil {
			continue
		}
		fk := *nodes[i].room_membership_room
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(room.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "room_membership_room" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rmq *RoomMembershipQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rmq.querySpec()
	_spec.Node.Columns = rmq.ctx.Fields
	if len(rmq.ctx.Fields) > 0 {
		_spec.Unique = rmq.ctx.Unique != nil && *rmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rmq.driver, _spec)
}

func (rmq *RoomMembershipQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(roommembership.Table, roommembership.Columns, sqlgraph.NewFieldSpec(roommembership.FieldID, field.TypeInt))
	_spec.From = rmq.sql
	if unique := rmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rmq.path != nil {
		_spec.Unique = true
	}
	if fields := rmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roommembership.FieldID)
		for i := range fields {
			if fields[i] != roommembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rmq *RoomMembershipQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rmq.driver.Dialect())
	t1 := builder.Table(roommembership.Table)
	columns := rmq.ctx.Fields
	if len(columns) == 0 {
		columns = roommembership.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rmq.sql != nil {
		selector = rmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rmq.ctx.Unique != nil && *rmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rmq.predicates {
		p(selector)
	}
	for _, p := range rmq.order {
		p(selector)
	}
	if offset := rmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoomMembershipGroupBy is the group-by builder for RoomMembership entities.
type RoomMembershipGroupBy struct {
	selector
	build *RoomMembershipQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rmgb *RoomMembershipGroupBy) Aggregate(fns ...AggregateFunc) *RoomMembershipGroupBy {
	rmgb.fns = append(rmgb.fns, fns...)
	return rmgb
}

// Scan applies the selector query and scans the result into the given value.
func (rmgb *RoomMembershipGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rmgb.build.ctx, "GroupBy")
	if err := rmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoomMembershipQuery, *RoomMembershipGroupBy](ctx, rmgb.build, rmgb, rmgb.build.inters, v)
}

func (rmgb *RoomMembershipGroupBy) sqlScan(ctx context.Context, root *RoomMembershipQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rmgb.fns))
	for _, fn := range rmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rmgb.flds)+len(rmgb.fns))
		for _, f := range *rmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoomMembershipSelect is the builder for selecting fields of RoomMembership entities.
type RoomMembershipSelect struct {
	*RoomMembershipQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rms *RoomMembershipSelect) Aggregate(fns ...AggregateFunc) *RoomMembershipSelect {
	rms.fns = append(rms.fns, fns...)
	return rms
}

// Scan applies the selector query and scans the result into the given value.
func (rms *RoomMembershipSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rms.ctx, "Select")
	if err := rms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoomMembershipQuery, *RoomMembershipSelect](ctx, rms.RoomMembershipQuery, rms, rms.inters, v)
}

func (rms *RoomMembershipSelect) sqlScan(ctx context.Context, root *RoomMembershipQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rms.fns))
	for _, fn := range rms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
