// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/eleven-am/enclave/ent/calllog"
	"github.com/eleven-am/enclave/ent/callparticipant"
	"github.com/eleven-am/enclave/ent/contact"
	"github.com/eleven-am/enclave/ent/favourite"
	"github.com/eleven-am/enclave/ent/media"
	"github.com/eleven-am/enclave/ent/message"
	"github.com/eleven-am/enclave/ent/notification"
	"github.com/eleven-am/enclave/ent/room"
	"github.com/eleven-am/enclave/ent/roommembership"
	"github.com/eleven-am/enclave/ent/schema"
	"github.com/eleven-am/enclave/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	calllogFields := schema.CallLog{}.Fields()
	_ = calllogFields
	// calllogDescStartedAt is the schema descriptor for started_at field.
	calllogDescStartedAt := calllogFields[1].Descriptor()
	// calllog.DefaultStartedAt holds the default value on creation for the started_at field.
	calllog.DefaultStartedAt = calllogDescStartedAt.Default.(func() time.Time)
	// calllogDescCreatedAt is the schema descriptor for created_at field.
	calllogDescCreatedAt := calllogFields[3].Descriptor()
	// calllog.DefaultCreatedAt holds the default value on creation for the created_at field.
	calllog.DefaultCreatedAt = calllogDescCreatedAt.Default.(func() time.Time)
	callparticipantFields := schema.CallParticipant{}.Fields()
	_ = callparticipantFields
	// callparticipantDescJoinedAt is the schema descriptor for joined_at field.
	callparticipantDescJoinedAt := callparticipantFields[1].Descriptor()
	// callparticipant.DefaultJoinedAt holds the default value on creation for the joined_at field.
	callparticipant.DefaultJoinedAt = callparticipantDescJoinedAt.Default.(func() time.Time)
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescIsFavourite is the schema descriptor for is_favourite field.
	contactDescIsFavourite := contactFields[0].Descriptor()
	// contact.DefaultIsFavourite holds the default value on creation for the is_favourite field.
	contact.DefaultIsFavourite = contactDescIsFavourite.Default.(bool)
	// contactDescIsBlocked is the schema descriptor for is_blocked field.
	contactDescIsBlocked := contactFields[1].Descriptor()
	// contact.DefaultIsBlocked holds the default value on creation for the is_blocked field.
	contact.DefaultIsBlocked = contactDescIsBlocked.Default.(bool)
	// contactDescAlias is the schema descriptor for alias field.
	contactDescAlias := contactFields[2].Descriptor()
	// contact.DefaultAlias holds the default value on creation for the alias field.
	contact.DefaultAlias = contactDescAlias.Default.(string)
	// contactDescCreatedAt is the schema descriptor for created_at field.
	contactDescCreatedAt := contactFields[3].Descriptor()
	// contact.DefaultCreatedAt holds the default value on creation for the created_at field.
	contact.DefaultCreatedAt = contactDescCreatedAt.Default.(func() time.Time)
	// contactDescUpdatedAt is the schema descriptor for updated_at field.
	contactDescUpdatedAt := contactFields[4].Descriptor()
	// contact.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	contact.DefaultUpdatedAt = contactDescUpdatedAt.Default.(func() time.Time)
	// contact.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	contact.UpdateDefaultUpdatedAt = contactDescUpdatedAt.UpdateDefault.(func() time.Time)
	favouriteFields := schema.Favourite{}.Fields()
	_ = favouriteFields
	// favouriteDescCreatedAt is the schema descriptor for created_at field.
	favouriteDescCreatedAt := favouriteFields[0].Descriptor()
	// favourite.DefaultCreatedAt holds the default value on creation for the created_at field.
	favourite.DefaultCreatedAt = favouriteDescCreatedAt.Default.(func() time.Time)
	mediaFields := schema.Media{}.Fields()
	_ = mediaFields
	// mediaDescFilename is the schema descriptor for filename field.
	mediaDescFilename := mediaFields[0].Descriptor()
	// media.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	media.FilenameValidator = mediaDescFilename.Validators[0].(func(string) error)
	// mediaDescContentType is the schema descriptor for content_type field.
	mediaDescContentType := mediaFields[1].Descriptor()
	// media.ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	media.ContentTypeValidator = mediaDescContentType.Validators[0].(func(string) error)
	// mediaDescStoragePath is the schema descriptor for storage_path field.
	mediaDescStoragePath := mediaFields[2].Descriptor()
	// media.StoragePathValidator is a validator for the "storage_path" field. It is called by the builders before save.
	media.StoragePathValidator = mediaDescStoragePath.Validators[0].(func(string) error)
	// mediaDescChecksum is the schema descriptor for checksum field.
	mediaDescChecksum := mediaFields[3].Descriptor()
	// media.ChecksumValidator is a validator for the "checksum" field. It is called by the builders before save.
	media.ChecksumValidator = mediaDescChecksum.Validators[0].(func(string) error)
	// mediaDescSizeBytes is the schema descriptor for size_bytes field.
	mediaDescSizeBytes := mediaFields[4].Descriptor()
	// media.SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	media.SizeBytesValidator = mediaDescSizeBytes.Validators[0].(func(int64) error)
	// mediaDescCreatedAt is the schema descriptor for created_at field.
	mediaDescCreatedAt := mediaFields[5].Descriptor()
	// media.DefaultCreatedAt holds the default value on creation for the created_at field.
	media.DefaultCreatedAt = mediaDescCreatedAt.Default.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCipherText is the schema descriptor for cipher_text field.
	messageDescCipherText := messageFields[0].Descriptor()
	// message.CipherTextValidator is a validator for the "cipher_text" field. It is called by the builders before save.
	message.CipherTextValidator = messageDescCipherText.Validators[0].(func(string) error)
	// messageDescContentType is the schema descriptor for content_type field.
	messageDescContentType := messageFields[1].Descriptor()
	// message.DefaultContentType holds the default value on creation for the content_type field.
	message.DefaultContentType = messageDescContentType.Default.(string)
	// messageDescEncryptionScheme is the schema descriptor for encryption_scheme field.
	messageDescEncryptionScheme := messageFields[2].Descriptor()
	// message.DefaultEncryptionScheme holds the default value on creation for the encryption_scheme field.
	message.DefaultEncryptionScheme = messageDescEncryptionScheme.Default.(string)
	// messageDescEdited is the schema descriptor for edited field.
	messageDescEdited := messageFields[3].Descriptor()
	// message.DefaultEdited holds the default value on creation for the edited field.
	message.DefaultEdited = messageDescEdited.Default.(bool)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[4].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescUpdatedAt is the schema descriptor for updated_at field.
	messageDescUpdatedAt := messageFields[5].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() time.Time)
	// message.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	message.UpdateDefaultUpdatedAt = messageDescUpdatedAt.UpdateDefault.(func() time.Time)
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescKind is the schema descriptor for kind field.
	notificationDescKind := notificationFields[0].Descriptor()
	// notification.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	notification.KindValidator = notificationDescKind.Validators[0].(func(string) error)
	// notificationDescCipherText is the schema descriptor for cipher_text field.
	notificationDescCipherText := notificationFields[1].Descriptor()
	// notification.CipherTextValidator is a validator for the "cipher_text" field. It is called by the builders before save.
	notification.CipherTextValidator = notificationDescCipherText.Validators[0].(func(string) error)
	// notificationDescEncryptionScheme is the schema descriptor for encryption_scheme field.
	notificationDescEncryptionScheme := notificationFields[2].Descriptor()
	// notification.DefaultEncryptionScheme holds the default value on creation for the encryption_scheme field.
	notification.DefaultEncryptionScheme = notificationDescEncryptionScheme.Default.(string)
	// notificationDescRead is the schema descriptor for read field.
	notificationDescRead := notificationFields[3].Descriptor()
	// notification.DefaultRead holds the default value on creation for the read field.
	notification.DefaultRead = notificationDescRead.Default.(bool)
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationFields[4].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	// notificationDescUpdatedAt is the schema descriptor for updated_at field.
	notificationDescUpdatedAt := notificationFields[5].Descriptor()
	// notification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notification.DefaultUpdatedAt = notificationDescUpdatedAt.Default.(func() time.Time)
	// notification.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notification.UpdateDefaultUpdatedAt = notificationDescUpdatedAt.UpdateDefault.(func() time.Time)
	roomFields := schema.Room{}.Fields()
	_ = roomFields
	// roomDescName is the schema descriptor for name field.
	roomDescName := roomFields[0].Descriptor()
	// room.NameValidator is a validator for the "name" field. It is called by the builders before save.
	room.NameValidator = roomDescName.Validators[0].(func(string) error)
	// roomDescDescription is the schema descriptor for description field.
	roomDescDescription := roomFields[1].Descriptor()
	// room.DefaultDescription holds the default value on creation for the description field.
	room.DefaultDescription = roomDescDescription.Default.(string)
	// roomDescIsPrivate is the schema descriptor for is_private field.
	roomDescIsPrivate := roomFields[2].Descriptor()
	// room.DefaultIsPrivate holds the default value on creation for the is_private field.
	room.DefaultIsPrivate = roomDescIsPrivate.Default.(bool)
	// roomDescIsDirect is the schema descriptor for is_direct field.
	roomDescIsDirect := roomFields[3].Descriptor()
	// room.DefaultIsDirect holds the default value on creation for the is_direct field.
	room.DefaultIsDirect = roomDescIsDirect.Default.(bool)
	// roomDescCreatedAt is the schema descriptor for created_at field.
	roomDescCreatedAt := roomFields[4].Descriptor()
	// room.DefaultCreatedAt holds the default value on creation for the created_at field.
	room.DefaultCreatedAt = roomDescCreatedAt.Default.(func() time.Time)
	// roomDescUpdatedAt is the schema descriptor for updated_at field.
	roomDescUpdatedAt := roomFields[5].Descriptor()
	// room.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	room.DefaultUpdatedAt = roomDescUpdatedAt.Default.(func() time.Time)
	// room.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	room.UpdateDefaultUpdatedAt = roomDescUpdatedAt.UpdateDefault.(func() time.Time)
	roommembershipFields := schema.RoomMembership{}.Fields()
	_ = roommembershipFields
	// roommembershipDescCanPost is the schema descriptor for can_post field.
	roommembershipDescCanPost := roommembershipFields[1].Descriptor()
	// roommembership.DefaultCanPost holds the default value on creation for the can_post field.
	roommembership.DefaultCanPost = roommembershipDescCanPost.Default.(bool)
	// roommembershipDescCanCall is the schema descriptor for can_call field.
	roommembershipDescCanCall := roommembershipFields[2].Descriptor()
	// roommembership.DefaultCanCall holds the default value on creation for the can_call field.
	roommembership.DefaultCanCall = roommembershipDescCanCall.Default.(bool)
	// roommembershipDescJoinedAt is the schema descriptor for joined_at field.
	roommembershipDescJoinedAt := roommembershipFields[3].Descriptor()
	// roommembership.DefaultJoinedAt holds the default value on creation for the joined_at field.
	roommembership.DefaultJoinedAt = roommembershipDescJoinedAt.Default.(func() time.Time)
	// roommembershipDescUpdatedAt is the schema descriptor for updated_at field.
	roommembershipDescUpdatedAt := roommembershipFields[4].Descriptor()
	// roommembership.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	roommembership.DefaultUpdatedAt = roommembershipDescUpdatedAt.Default.(func() time.Time)
	// roommembership.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	roommembership.UpdateDefaultUpdatedAt = roommembershipDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[1].Descriptor()
	// user.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	user.DisplayNameValidator = userDescDisplayName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescLastSeenAt is the schema descriptor for last_seen_at field.
	userDescLastSeenAt := userFields[6].Descriptor()
	// user.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	user.DefaultLastSeenAt = userDescLastSeenAt.Default.(func() time.Time)
	// user.UpdateDefaultLastSeenAt holds the default value on update for the last_seen_at field.
	user.UpdateDefaultLastSeenAt = userDescLastSeenAt.UpdateDefault.(func() time.Time)
}
